from django.urls import path
from vendors import views, products, shops, orders
from vendors.products import VProductsListJson

urlpatterns = [
    path("", views.index, name="index"),
    path("products_filter", products.product_filter, name="products_filter"),
    path("products/<uidb64>", products.index, name="products"),
    path("vproducts-table", VProductsListJson.as_view(), name="vproducts-table"),
    path("storproducts/", products.addrecord, name="storproducts"),
    path("storall/", products.addprodtoshop, name="storall"),
    path("productsedit/<int:id>", products.edita, name="productsedit"),
    path("updateproducts", products.updaterecord, name="updateproducts"),
    path("deleteproducts/<int:id>", products.delete, name="deleteproducts"),
    path("shops/", shops.index, name="shops"),
    path("storeshop/", shops.addrecord, name="storeshop"),
    path("picksshop/<int:id>", shops.edita, name="shopedit"),
    path("updateshop", shops.updaterecord, name="updateshop"),
    path("deleteshop/<int:id>", shops.delete, name="deleteshop"),
    path("orders/", orders.index, name="orders"),
    path("delays/", orders.delay, name="delays"),
    path("closed/", orders.closed, name="closed"),
    path("orderdetails/<str:serial>", orders.order_detail, name="orderdetails"),
    path("ordersedit/<str:id>", orders.edita, name="ordersedit"),
    path("updateorders", orders.updaterecord, name="updateorders"),
    path("sales_filter", orders.sales_filter, name="sales_filter"),
    path("vsales", orders.sales_report, name="vsales"),
    path("vnvreviews", orders.nreviews, name="vnvreviews"),
    path("vareviews", orders.allreviews, name="vareviews"),
    path("checkreviews/<int:id>", orders.checkreview, name="checkreviews"),
    path("vtracker", orders.tracker, name="vtracker"),
    path("vconfdelivery/<int:id>", orders.dconf, name="vconfdelivery"),
    path("vtrackerdelays", orders.dtracker, name="vtrackerdelays"),
    path("vtrackercompleted", orders.ctracker, name="vtrackercompleted"),
    path("vprofile", views.profile, name="vprofile"),
    path("update_vendor_details", views.updaterecord, name="update_vendor_details"),
    path("uploadvdocs", views.uploadDocs, name="uploadvdocs"),
    path("vuploadsview/<int:id>", views.uviews, name="vuploadsview"),
    path("editvdocs", views.editDocs, name="editvdocs"),
    path("vdocsview/<int:id>", views.vdocsview, name="vdocsview"),
]
