# Generated by Django 4.1.1 on 2022-10-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cover',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
