# Generated by Django 4.1.1 on 2022-10-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_products_cover_products_serial_pimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pimages',
            old_name='Cover',
            new_name='cover',
        ),
    ]
