# Generated by Django 4.1.1 on 2022-10-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_rename_cover_pimages_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Brands', 'verbose_name_plural': 'Product_Brands'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categories', 'verbose_name_plural': 'Product_Categories'},
        ),
        migrations.AlterModelOptions(
            name='munits',
            options={'verbose_name': 'Munits', 'verbose_name_plural': 'Product_Measurement_Units'},
        ),
        migrations.AlterModelOptions(
            name='pimages',
            options={'verbose_name': 'Pimages', 'verbose_name_plural': 'Product_Images'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='brands',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='munits',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pimages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
