# Generated by Django 4.1.1 on 2022-10-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_brands_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
