# Generated by Django 4.1.1 on 2023-02-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_products_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categories',
            name='slide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='slide',
            field=models.BooleanField(default=False),
        ),
    ]
