# Generated by Django 4.1.1 on 2022-10-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_products_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cover',
            field=models.ImageField(default='products/none.png', upload_to='products/'),
        ),
    ]
