# Generated by Django 4.1.1 on 2022-11-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
