from django.urls import path
from . import views,order,shop, vendor, gigs
from mpesa.views import lipa_cart, lipa_conf

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('hw/', views.hw, name='hw'),
    path('product_profile/<uidb64>', views.product_profile, name='product_profile'),
    path('checkreviews/<int:id>', views.find_review, name='checkreviews'),
    path('addreview/', views.addreview, name='addreview'),
    path('editreview/', views.editreview, name='editreview'),
    path('add_wish/<int:id>', views.addwish, name='add_wish'),
    path('product_listings/<uidb64>', shop.index, name='product_listings'),
    path('product_lists/<uidb64>', shop.shop_list, name='product_lists'),
    path('updatelocation/<int:id>', shop.updatelocation, name='updatelocation'),
    path('search/', shop.search, name='search'),
    path('all_products/', shop.allproducts, name='all_products'),
    path('all_products_lists/', shop.allproductslists, name='all_products_lists'),
    path('all_discounts/', shop.alldiscounts, name='all_discounts'),
    path('all_discounts_lists/', shop.alldiscountslists, name='all_discounts_lists'),
    path('addcart/', order.addrecord, name='addcart'),
    path('quick_cart/', order.quickadd, name='quick_cart'),
    path('updatecart/', order.updaterecord, name='updatecart'),
    path('ctals/', views.cart_totals, name='ctals'),
    path('clocs/', views.cart_locations, name='clocs'),
    path('product_carts/<uidb64>', order.product_cart, name='product_carts'),
    path('nums/', order.c_quantity, name='nums'),
    path('order_summary/<str:serial>', order.order_detail, name='order_summary'),
    path('create_order_c/', order.createorder, name='create_order_c'),
    path('delcartitem/<int:id>', order.delete, name='delcartitem'),
    path('gdelcartitem/<int:id>', order.gdelete, name='gdelcartitem'),
    path('vendor_store/<uidb64>', vendor.index, name='vendor_store'),
    path('vendor_store_list/<uidb64>', vendor.slists, name='vendor_store_list'),
    path('shop_product_listings/<sidb64>/<uidb64>', vendor.listing, name='shop_product_listings'),
    path('shop_product_lists/<sidb64>/<uidb64>', vendor.slisting, name='shop_product_lists'),
    path('all_vendors/', vendor.allvendors, name='all_vendors'),
    path('gigs/', gigs.allpitems, name='gigs'),
    path('gproduct_profile/<uidb64>', gigs.product_profile, name='gproduct_profile'),
    path('paddcart/', gigs.addrecord, name='paddcart'),
    path('pupdatecart/', gigs.updaterecord, name='pupdatecart'),
    path('pquick_cart/', gigs.quickadd, name='pquick_cart'),
    path('reqadd/', gigs.addrequest, name='reqadd'),
    path('gproduct_listings/<uidb64>', gigs.finder, name='gproduct_listings'),
    path('gigs_lists/', gigs.allpitemslists, name='gigs_lists'),
    path('gigs_lists_filter/<uidb64>', gigs.finderl, name='gigs_lists_filter'),
    path('psearch/', gigs.search, name='psearch'),
    path('ereqdets/<int:id>', gigs.edita, name='ereqdets'),
    path('grequpdate/', gigs.updatecreq, name='grequpdate'),
    path('job_summary/<uidb64>', order.job_detail, name='job_summary'),
    path('payloader/<int:id>', views.pload, name='payloader'),
    path('pushpay', lipa_cart, name='pushpay'),
    path('pushconf', lipa_conf, name='pushconf'),
    path('gskill_listings/<uidb64>', gigs.findskills, name='gskill_listings'),
    path('gsearch_listings/<uidb64>', gigs.finderskills, name='gsearch_listings'),
    path('eskillsget/<int:id>', gigs.skillsget, name='eskillsget'),
]
