# Generated by Django 4.1.1 on 2022-12-20 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_profile_is_approved_customuser_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vdocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idfront', models.ImageField(default='documents/none.png', upload_to='documents/')),
                ('idback', models.ImageField(default='documents/none.png', upload_to='documents/')),
                ('bizreg', models.ImageField(default='documents/none.png', upload_to='documents/')),
                ('taxcomp', models.ImageField(default='documents/none.png', upload_to='documents/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vdocs',
                'verbose_name_plural': 'Vendor_Documents',
            },
        ),
        migrations.DeleteModel(
            name='Udocs',
        ),
    ]
