# Generated by Django 4.1.1 on 2022-12-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_profile_is_approved_customuser_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_details',
            field=models.BooleanField(default=False),
        ),
    ]
