# Generated by Django 4.1.1 on 2023-03-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_profile_has_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymeta',
            name='about',
            field=models.TextField(default='None'),
        ),
    ]
