# Generated by Django 4.1.1 on 2023-03-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_customuser_locker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='locker',
            new_name='location',
        ),
    ]
