# Generated by Django 4.1.1 on 2023-04-09 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_cartmeta_customer'),
        ('accounts', '0026_profile_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='county',
            field=models.ForeignKey(blank=True, default=29, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countyp', to='management.counties'),
        ),
    ]
