# Generated by Django 4.1.1 on 2023-11-10 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_modules_usertypes_actions_permissions'),
        ('accounts', '0027_alter_profile_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usertype',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.usertypes'),
        ),
    ]
