"""
Django settings for susrecom project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v)^w1v$69h8!5c5t(ct3wlb^hfn@x+flnsy+$gfla=)++qh4s%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'accounts.CustomUser'
AUTHENTICATION_BACKENDS = ['accounts.backends.EmailBackend']

# Application definition

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = '145.239.19.134'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'alerts@jagedo.co.ke'
EMAIL_HOST_PASSWORD = 'alerts@2023'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'alerts@jagedo.co.ke'

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'accounts.apps.AccountsConfig',
    'core.apps.CoreConfig',
    'items.apps.ItemsConfig',
    'management.apps.ManagementConfig',
    'vendors.apps.VendorsConfig',
    'customers.apps.CustomersConfig',
    'logistics.apps.LogisticsConfig',
    'experts.apps.ExpertsConfig',
    'mpesa.apps.MpesaConfig',
    'django_cleanup.apps.CleanupConfig',
    'chat.apps.ChatConfig',
    'crispy_forms',
    'rest_framework',
    'django_crontab',
    'import_export',
    'whitenoise.runserver_nostatic',
    
    
]



CRISPY_TEMPLATE_PACK = 'bootstrap4'

CSRF_TRUSTED_ORIGINS = ['https://jagedo.co.ke']

SECURE_SSL_REDIRECT = True 




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

]

ROOT_URLCONF = 'susrecom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'susrecom.wsgi.application'

VERIFICATION_TOKEN = 'PYLkv6kIy8UsbANJfhLbBtMS'
OAUTH_ACCESS_TOKEN = '1b124fa942e7be935f20ed0738f70712'
BOT_USER_ACCESS_TOKEN = 'xoxb-4714609293319-4714719586327-hVLLRFZV48RroSNaQ3476ji5'
CLIENT_ID = '4714609293319.4741820344641'
CLIENT_SECRET = '26d1fdc20f6d3361e4cbd5a0939624e1'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'susrecom_jenga',
        'USER': 'jagedo',
        'PASSWORD': 'Milana@17',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        },
    },
    
]



# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, 'static')
#]
if DEBUG:
	STATICFILES_DIRS = [
		os.path.join(BASE_DIR, 'static')
   ]
else:
	STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATIC_ROOT = '/home/jagedo/jagedo/jportal/susrecom/static'

MEDIA_URL = 'media/'
#MEDIA_ROOT = '/home/jagedo/jagedo/jagedo-orig/media'
MEDIA_ROOT = '/home/jagedo/jagedo/jportal/susrecom/media'
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

LOGIN_REDIRECT_URL = '/accs/lswitch/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'
