# Generated by Django 4.1.1 on 2022-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_shops_vproducts_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vproducts',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
