# Generated by Django 4.1.1 on 2022-10-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vproducts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vproducts',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
