# Generated by Django 4.1.1 on 2022-11-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vproducts_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
