# Generated by Django 4.1.1 on 2022-11-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_shops_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vproducts',
            options={'ordering': ['price']},
        ),
    ]
