# Generated by Django 4.1.1 on 2023-04-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_shops_is_fundi_vproducts_is_fundi'),
    ]

    operations = [
        migrations.AddField(
            model_name='vproducts',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
