# Generated by Django 4.1.1 on 2022-12-27 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experts', '0003_wdays'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wdays',
            options={'ordering': ('id',), 'verbose_name': 'Wdays', 'verbose_name_plural': 'Work_Days'},
        ),
        migrations.CreateModel(
            name='PartnerTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.wdays')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PartnerTimes',
                'verbose_name_plural': 'Partner_Availability',
            },
        ),
        migrations.CreateModel(
            name='PartnerSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.fields')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.skills')),
            ],
            options={
                'verbose_name': 'PartnerSkills',
                'verbose_name_plural': 'Partner_Skills',
            },
        ),
        migrations.CreateModel(
            name='PartnerMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(default=0)),
                ('regas', models.IntegerField(default=0)),
                ('yrs', models.IntegerField(default=0)),
                ('availability', models.IntegerField(default=0)),
                ('cv', models.ImageField(default='documents/none.png', upload_to='documents/')),
                ('idfront', models.ImageField(default='documents/none.png', upload_to='documents/')),
                ('idback', models.ImageField(default='documents/none.png', upload_to='documents/')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.fields')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PartnerMeta',
                'verbose_name_plural': 'Partner_Details',
            },
        ),
        migrations.CreateModel(
            name='PartnerCerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.ImageField(default='documents/none.png', upload_to='documents/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.certs')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PartnerCerts',
                'verbose_name_plural': 'Partner_Certificates',
            },
        ),
    ]
