# Generated by Django 4.1.1 on 2022-12-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_cartmeta_customer'),
        ('experts', '0004_alter_wdays_options_partnertimes_partnerskills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermeta',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.counties'),
        ),
    ]
