# Generated by Django 4.1.1 on 2023-01-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0016_quote_milestones_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_milestones',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote_milestones',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote_milestones',
            name='pcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
