# Generated by Django 4.1.1 on 2023-02-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0017_quote_milestones_fee_quote_milestones_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cover', models.ImageField(default='cats/none.png', upload_to='cats/')),
                ('status', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ExpertCats',
                'verbose_name_plural': 'Expert_Categories',
            },
        ),
        migrations.CreateModel(
            name='ExpertSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cover', models.ImageField(default='cats/none.png', upload_to='cats/')),
                ('status', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.expertcats')),
            ],
            options={
                'verbose_name': 'ExpertSkills',
                'verbose_name_plural': 'Expert_Skills',
            },
        ),
    ]
