# Generated by Django 4.1.1 on 2023-02-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0020_remove_expertskills_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
