# Generated by Django 4.1.1 on 2023-08-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0021_quotations_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermeta',
            name='approval_doc',
            field=models.ImageField(default='documents/none.png', upload_to='documents/'),
        ),
    ]
