# Generated by Django 4.1.1 on 2023-08-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0023_contractorcategory_ncafields_contractorportfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorportfolio',
            name='title',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
    ]
