# Generated by Django 4.1.1 on 2023-04-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_legaldocuments_user_legaldocumenttypes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocumenttypes',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legaldocumenttypes',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legaldocumenttypes',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
