# Generated by Django 4.1.1 on 2022-12-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_certs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wdays',
                'verbose_name_plural': 'Work_Days',
            },
        ),
    ]
