# Generated by Django 4.1.1 on 2023-01-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Pcategories',
        ),
        migrations.AlterModelOptions(
            name='pcategories',
            options={'verbose_name': 'Pcategories', 'verbose_name_plural': 'Expert_Product_Categories'},
        ),
    ]
