# Generated by Django 4.1.1 on 2023-01-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0008_pitems_peimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
