# Generated by Django 4.1.1 on 2023-01-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0009_pitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='peimages',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitems',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pitems',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.partnermeta'),
        ),
    ]
