# Generated by Django 4.1.1 on 2023-01-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0012_quotations_quote_milestones_quote_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_milestones',
            name='price',
        ),
        migrations.AlterField(
            model_name='quote_items',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
