# Generated by Django 4.1.1 on 2023-01-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0013_remove_quote_milestones_price_alter_quote_items_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
