# Generated by Django 4.1.1 on 2023-01-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0014_quotations_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
