# Generated by Django 4.1.1 on 2023-01-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0015_quotations_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_milestones',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
