# Generated by Django 4.1.1 on 2023-02-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0018_expertcats_expertskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertskills',
            name='description',
            field=models.TextField(default='None'),
        ),
    ]
