# Generated by Django 4.1.1 on 2023-01-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tpaycarts_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpaycarts',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tpaycarts',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
