# Generated by Django 4.1.1 on 2023-02-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tpaycarts_is_paid_tpaycarts_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
