# Generated by Django 4.1.1 on 2023-02-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0020_remove_expertskills_description_and_more'),
        ('core', '0008_jobs_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcarts',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.expertskills'),
        ),
        migrations.AlterField(
            model_name='pcarts',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.expertcats'),
        ),
    ]
