# Generated by Django 4.1.1 on 2023-04-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_products_price'),
        ('core', '0014_jobs_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='vproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.products'),
        ),
    ]
