# Generated by Django 4.1.1 on 2023-04-08 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0012_products_price'),
        ('core', '0019_alter_carts_vproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercarts',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendoroc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordercarts',
            name='vproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.products'),
        ),
    ]
