# Generated by Django 4.1.1 on 2023-04-08 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_ordercarts_vendor_alter_ordercarts_vproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendoro', to=settings.AUTH_USER_MODEL),
        ),
    ]
