# Generated by Django 4.1.1 on 2023-04-09 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_vproducts_cost'),
        ('core', '0024_ordercarts_is_assigned_orders_is_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercarts',
            name='vendor',
        ),
        migrations.AddField(
            model_name='ordercarts',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.shops'),
        ),
    ]
