# Generated by Django 4.1.1 on 2023-04-09 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_vproducts_cost'),
        ('core', '0026_remove_orders_vendor_orders_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='vendor',
        ),
        migrations.AddField(
            model_name='reviews',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.shops'),
        ),
    ]
