# Generated by Django 4.1.1 on 2023-04-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_legaldocumenttypes_legaldocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocumenttypes',
            name='is_global',
            field=models.BooleanField(default=True),
        ),
    ]
