# Generated by Django 4.1.1 on 2022-10-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('accounts', '0008_companymeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.ForeignKey(blank=True, default=48, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.counties'),
        ),
    ]
