# Generated by Django 4.1.1 on 2022-10-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='county',
        ),
    ]
