# Generated by Django 4.1.1 on 2022-11-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymeta',
            name='address',
            field=models.CharField(default='Nairobi', max_length=255),
        ),
        migrations.AddField(
            model_name='companymeta',
            name='email',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
