# Generated by Django 4.1.1 on 2022-11-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymeta',
            name='dd_office',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymeta',
            name='dd_vendor',
            field=models.IntegerField(default=0),
        ),
    ]
