# Generated by Django 4.1.1 on 2023-03-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_companymeta_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='locker',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
