# Generated by Django 4.1.1 on 2023-01-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_cartmeta_customer'),
        ('core', '0002_jobs_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.pickups'),
        ),
    ]
