# Generated by Django 4.1.1 on 2023-01-05 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0010_peimages_status_pitems_status_alter_pitems_expert'),
        ('core', '0003_jobs_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.skills'),
        ),
    ]
