# Generated by Django 4.1.1 on 2023-01-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carts_is_paid_tpaycarts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpaycarts',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
