# Generated by Django 4.1.1 on 2023-03-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_jobs_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='directions',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
