# Generated by Django 4.1.1 on 2023-04-08 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_vproducts_cost'),
        ('core', '0017_alter_carts_vproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='vproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vproducts'),
        ),
    ]
