# Generated by Django 4.1.1 on 2023-04-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_reviews_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercarts',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
