# Generated by Django 4.1.1 on 2022-11-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_alter_vproducts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vproducts',
            options={},
        ),
    ]
